#!/bin/bash

# Function to display help message
show_help() {
  echo "Usage: $0 [mac|linux|win|all]"
  echo "Execute the script based on the provided argument."
  echo "  mac   Build app for Mac"
  echo "  linux Build app for linux"
  echo "  win   Build app for windows"
  echo "  all   Build app for all platforms"
}

# Check if no arguments are provided
if [ "$#" -eq 0 ]; then
  echo "Error: Please provide an argument."
  show_help
  exit 1
fi

# Check for help option
if [ "$1" == "--help" ]; then
  show_help
  exit 0
fi

# Check the provided argument
case $1 in
  mac)
    rm -rf dist/mac_*
    ./building/patch.sh
    ./building/build-mac.sh
    ;;
  linux)
    rm -rf dist/linux_*
    ./building/patch.sh
    ./building/build-linux.sh
    ;;
  win)
    rm -rf dist/win_*
    ./building/patch.sh
    ./building/build-win.sh
    ;;
  all)
    rm -rf dist/*
    ./building/patch.sh
    ./building/build-mac.sh
    ./building/build-win.sh
    ./building/build-linux.sh
    ;;
  *)
    echo "Error: Invalid argument. Please use 'mac', 'linux', or 'win'."
    show_help
    exit 1
    ;;
esac

exit 0
